### ISSUE TITLE
Propose (and implement) a way to manage assets.

### ISSUE THREAD

**Issue by dchaplinsky** [mrgambal/vulyk#10]
Each plugin might have optional JS and CSS assets that it should expose to the framework

We have webassets/Flask-webassets on board already to work with merges that belongs to the framework (check assets.py for details).

On plugin pages we want to include both types of merges, those from framework and those from current plugin (so plugin might talk to frameworks methods defined in Vulyk object).

Please investigate if we can use webassets to manage plugin's assets as well. Take into account, that at least CSS assets for plugin aren't mandatory.

Please reflect that in documentation.

**Comment by dchaplinsky** [comment]
#15

**Comment by mrgambal** [comment]
Forsaken and forgotten issue... rest in peace.
