### ISSUE TITLE
Building wheels for collected packages: rjsmin ERROR

### ISSUE THREAD

**Issue by josedandrade** [mrgambal/vulyk#112]
I am trying to install and run. I get an error executing this installation command:

pip install -e ../vulyk-declaration

I am running Ubuntu on WSL2 Windows 10

Description:    Ubuntu 20.04.1 LTS
Release:        20.04

Building wheels for collected packages: rjsmin
  Building wheel for rjsmin (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /mnt/c/Projects/sandbox/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e315onj0/rjsmin/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e315onj0/rjsmin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-cxcv1bo0
       cwd: /tmp/pip-install-e315onj0/rjsmin/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  copying ./rjsmin.py -> build/lib.linux-x86_64-3.8
  running build_ext
  building '_rjsmin' extension
  creating build/temp.linux-x86_64-3.8
  gcc -pthread -B /home/dandrade/anacondawsl/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/mnt/c/Projects/sandbox/venv/include -I/home/dandrade/anacondawsl/include/python3.8 -c rjsmin.c -o build/temp.linux-x86_64-3.8/rjsmin.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for rjsmin
  Running setup.py clean for rjsmin
Failed to build rjsmin
Installing collected packages: rjsmin, translitua, wheel, unicodecsv, XlsxWriter, vulyk-declaration
  Attempting uninstall: rjsmin
    Found existing installation: rjsmin 1.1.0
    Uninstalling rjsmin-1.1.0:

**Comment by mrgambal** [comment]
Hello @josedandrade ! Did you try installing `build-essential` package before setting up the Vulyk? I hope this should help:

```shell
sudo apt update
sudo apt install build-essential
```

Frankly, I don't have the Windows-based development environment right now, alas. But I presume the main cause is lack of pre-built binaries for python 3.8, as the `rjsmin` project didn't get updates for like 13 months. That's being said, if the `build-essential` package doesn't help, another possible solution could be in using Python 3.7.

Cheers!
