### ISSUE TITLE
Integrate our first real plugin: POS tagger.

### ISSUE THREAD

**Issue by dchaplinsky** [mrgambal/vulyk#12]
I've added a new branch dc-not-so-dummy-task that contains file with tasks, which is importable.

I've created frontend part (it might be slightly changed but essentials are there), it's available here:
https://dl.dropboxusercontent.com/u/4366002/pos_demo.html. As you might see in the code, it's already can render tasks using handlebars.

Once #9 and #10 is in, it would be nice to integrate it (including required assets).

**Comment by hotsyk** [comment]
Started working on this, as separate package, here - https://github.com/hotsyk/vulyk-tagging
