### ISSUE TITLE
We need "default" group

### ISSUE THREAD

**Issue by dchaplinsky** [mrgambal/vulyk#16]
We need "default" group which is always available and assigned to all newly created users.

Groups managing with CLI is a pain now, and 80% of use-cases will be “just allow users to do some work”. Having default group will simplify that to one command: manage.py group addtype ...

**Comment by mrgambal** [comment]
@dchaplinsky should it be closed after #20 and #22 ?

**Comment by mrgambal** [comment]
I feel no traces life here... Let it requiescat in pace.
:checkered_flag:
