### ISSUE TITLE
Concept of batches.

### ISSUE THREAD

**Issue by dchaplinsky** [mrgambal/vulyk#32]
We need to migrate concept of batches from unshred.it.

Idea here is following: Tasks are imported in batches. Tasks in the feed for the user is also ordered by batch, so user will receive all tasks from batch that comes first before next batch will be started.

This is a requirement because we don't want our results to be spread across 20000 of declarations with average of 0.5 response for each declaration. We want first 200 declarations (say, from ministry of ecology) to be done first with 3 responses per decl.

**Comment by dchaplinsky** [comment]
https://github.com/dchaplinsky/unshred-tag/blob/1230f9bbdf63e35dd253048521d1b05796071846/control.py#L52
https://github.com/dchaplinsky/unshred-tag/blob/1230f9bbdf63e35dd253048521d1b05796071846/app.py#L52

https://github.com/dchaplinsky/unshred-tag/blob/1230f9bbdf63e35dd253048521d1b05796071846/cli/load_to_mongo.py#L102

https://github.com/dchaplinsky/unshred-tag/blob/1230f9bbdf63e35dd253048521d1b05796071846/cli/load_to_mongo.py#L137

**Comment by mrgambal** [comment]
Does #41 cover all the aspects we need at the moment?
