### ISSUE TITLE
Missing favicon

### ISSUE THREAD

**Issue by balabanov** [mrgambal/vulyk#33]
#### Environment:

https://vulyk.herokuapp.com, any browser

#### Steps to reproduce:

* Authorize via Facebook
* Load first declaration

#### Actual result:

404 Missing favicon: https://vulyk.herokuapp.com/favicon.ico

#### Expected result:

Some icon added, at least a stub one

**Comment by mrgambal** [comment]
Was fixed long ago. Closing now.
