### ISSUE TITLE
Authorize Travis to get push hooks from repo

### ISSUE THREAD

**Issue by hotsyk** [mrgambal/vulyk#5]
Please sign here https://travis-ci.org/mrgambal/vulyk and authorize Travis to get push hooks, so project will be rebuilt on every push. 

Thanks!

**Comment by mrgambal** [comment]
Should switchin' the project on at the profile's dashboard be enough?
If so – I've enabled it.

**Comment by hotsyk** [comment]
Thanks, it is working
