### ISSUE TITLE
Enable python3 on readTheDocs for the project

### ISSUE THREAD

**Issue by mrgambal** [mrgambal/vulyk#79]
Please check and enable python 3 as the runner for documentation builds here on [RTD](https://readthedocs.org/projects/vulyk/).
The project is targeted only for python 3.4+, however its documentation is still being built using

```shell
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/vulyk/envs/latest
```

which causes:

```python
  File "/home/docs/checkouts/readthedocs.org/user_builds/vulyk/checkouts/latest/vulyk/models/task_types.py", line 174
    yield from map(lambda a: a.as_dict(),
             ^
SyntaxError: invalid syntax
```

and lacunas in the final documentation.

**Comment by dchaplinsky** [comment]
Can you check it now?

**Comment by mrgambal** [comment]
Amazing, thanks.
